//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagementSystem.Models
{
    using System;
    using System.Collections.Generic;

    public partial class order
    {
        //Database Constructors
        public byte order_id { get; set; }
        public Nullable<byte> order_productID { get; set; }
        public Nullable<decimal> order_price { get; set; }
        public Nullable<int> order_quantity { get; set; }
        public Nullable<System.DateTime> order_timestamp { get; set; }

        //Local Constructors
        public string order_productName { get; set; }
        public string order_series { get; set; }

        public virtual product product { get; set; }
    }
}
