//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class product
    {
        //Database Constructors
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public product()
        {
            this.orders = new HashSet<order>();
        }
        public byte product_id { get; set; }

        [DisplayFormat(ConvertEmptyStringToNull = false)]
        [Required(ErrorMessage = "This field is required.")]
        public string product_name { get; set; }

        [DisplayFormat(ConvertEmptyStringToNull = false)]
        [Required(ErrorMessage = "This field is required.")]
        public Nullable<decimal> product_price { get; set; }

        public Nullable<byte> product_series { get; set; }
        public string product_narration { get; set; }
        public string product_ingredients { get; set; }
        public string product_amounts { get; set; }
        public byte[] product_image { get; set; }
        public string product_units { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy/MM/dd}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> product_created { get; set; }

        //Local Constructors
        [DisplayFormat(ConvertEmptyStringToNull = true)]
        [Required(ErrorMessage = "This field is required.")]
        public List<string> ingredients { get; set; }

        [DisplayFormat(ConvertEmptyStringToNull = true)]
        [Required(ErrorMessage = "This field is required.")]
        public List<string> amounts { get; set; }
        public bool isAvailable { get; set; }
        public string ingredientString { get; set; }

        //Database generated
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order> orders { get; set; }
        public virtual series series { get; set; }
    }
}
