//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagementSystem.Models
{
    using System;
    using System.Collections.Generic;


    public partial class stock
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public stock()
        {
            this.stockTrans = new HashSet<stockTran>();
        }

        //Database Constructors
        public byte stock_id { get; set; }
        public string stock_name { get; set; }
        public string stock_category { get; set; }
        public string stock_unit { get; set; }
        public Nullable<decimal> stock_quantity { get; set; }
        public string stock_narration { get; set; }
        public Nullable<decimal> stock_capacity { get; set; }

        //Local Constructors
        public Nullable<System.DateTime> stock_date { get; set; }
        public int stock_warning { get; set; }
        public decimal percentage { get; set; }
        public decimal toAdd { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<stockTran> stockTrans { get; set; }
    }
}
