//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagementSystem.Models
{
    using System;
    using System.Collections.Generic;

    public partial class stockTran
    {
        //Database Constructors
        public byte stockTrans_id { get; set; }
        public Nullable<byte> stockTrans_stock { get; set; }
        public Nullable<System.DateTime> stockTrans_timestamp { get; set; }
        public string stockTrans_narration { get; set; }
        public string stockTrans_type { get; set; }
        public Nullable<decimal> stockTrans_value { get; set; }

        //Local Constructors
        public string stockTrans_stockName { get; set; }
        public string stockTrans_stockCategory { get; set; }
        public string stockTrans_stockUnit { get; set; }

        public virtual stock stock { get; set; }
    }
}
